name: Frontend Deployment On Push
on: 
    [push, workflow_dispatch]

jobs:
    testing: # job name
      runs-on: ubuntu-latest # Machine specs that the job will run on
      steps:
          - name: Checkout Repository # we need to checkout and install the repo basically coz the 
                                      # runner doesn't have access to our code

            uses: actions/checkout@v6 # pre-defined actinos from GH Marketplace
          - name: Set up Node.js
            uses: actions/setup-node@v6
          - name: Install Dependencies
            run: npm ci
            working-directory: ./02 Starting Project
          - name: Testing
            run: npm test
            working-directory: ./02 Starting Project
    deploy: # second job
      needs: [testing]
      runs-on: ubuntu-latest
      steps:
          - name: Checkout Repository # we need to checkout and install the repo basically coz the 
                                      # runner doesn't have access to our code

            uses: actions/checkout@v6 # pre-defined actinos from GH Marketplace
          - name: Set up Node.js
            uses: actions/setup-node@v6
          - name: Install Dependencies
            run: npm ci
            working-directory: ./02 Starting Project
          - name: Testing
            run: npm test
            working-directory: ./02 Starting Project
          - name: Build
            run: npm run build
            working-directory: ./02 Starting Project
          - name: Deploy
            run: echo "deploying..."

        