name: Testing 04 Practice Project
on: [push, workflow_dispatch]
jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repoistory
              uses: actions/checkout@v6
            - name: Set up Node.js
              uses: actions/setup-node@v6
            - name: Install Dependencies
              run: npm ci
              working-directory: ./04 Practice Project
            - name: Linting the project
              run: npx eslint --ext .jsx --fix src
              working-directory: ./04 Practice Project
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repoistory
              uses: actions/checkout@v6
            - name: Set up Node.js
              uses: actions/setup-node@v6
            - name: Install Dependencies
              run: npm ci
              working-directory: ./04 Practice Project
            - name: testing
              run: npm test
              working-directory: ./04 Practice Project
    build:
        runs-on: ubuntu-latest
        needs: [lint, test]
        steps:
            - name: Checkout Repoistory
              uses: actions/checkout@v6
            - name: Set up Node.js
              uses: actions/setup-node@v6
            - name: Install Dependencies
              run: npm ci
              working-directory: ./04 Practice Project
            - name: building
              run: npm run build
              working-directory: ./04 Practice Project
    output:
        runs-on: ubuntu-latest
        needs: [lint, test, build]
        steps:
          - name: Output Events Details
            run: echo ${{toJson(github.event_name)}}
